DROP TABLE IF EXISTS REGISTRATION;
CREATE TABLE REGISTRATION(
     id BIGINT AUTO_INCREMENT  PRIMARY KEY,
     username VARCHAR(250) NOT NULL,
     password VARCHAR(250) NOT NULL,
     confirm_password VARCHAR(250) NOT NULL,
     email VARCHAR(250) DEFAULT NULL                    
);
                            

DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE(
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	registrationid BIGINT NOT NULL,
	role VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS PROJECT;
CREATE TABLE PROJECT(
   project_id BIGINT AUTO_INCREMENT  PRIMARY KEY,
   project_name VARCHAR(50) NOT NULL
);
  
DROP TABLE IF EXISTS USER_PROJECT_MAPPING;
CREATE TABLE USER_PROJECT_MAPPING(
   project_mapping_id BIGINT AUTO_INCREMENT PRIMARY  KEY,
   project_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL
);

DROP TABLE IF EXISTS PROJECT_TASK;
CREATE TABLE PROJECT_TASK(
     project_task_id BIGINT AUTO_INCREMENT PRIMARY KEY,
     project_id BIGINT NOT NULL,
     task_name VARCHAR (250) NOT NULL,
     task_description VARCHAR (250) NOT NULL,
     start_date TIMESTAMP NOT NULL,
     end_date TIMESTAMP NOT NULL,
     start_work_date TIMESTAMP  NULL,
     end_work_date TIMESTAMP  NULL,
     task_status VARCHAR (50) NOT NULL
);
